---
on: [push, pull_request]

name: CI

jobs:
  test:
    name: Test
    strategy:
      matrix:
        sys:
          - os: ubuntu-latest
            rust_toolchain: "1.51"
          - os: ubuntu-latest
            rust_toolchain: stable
          - os: macos-latest
            rust_toolchain: stable
          - os: ubuntu-latest
            rust_toolchain: beta
          # - os: windows-2022
          #   rust_toolchain: stable-x86_64-pc-windows-gnu
    runs-on: ${{ matrix.sys.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.sys.rust_toolchain }}
          override: true
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
